version: '3'

services:
  nginx:
    build: ./nginx
    depends_on:
      - logstash
    ports:
      - 7070:8080
  logstash:
    build: ./logstash
    depends_on:
      - elasticsearch
    ports:
      - 5140:5140
  kibana:
    image: kibana:7.9.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  elasticsearch:
    image: elasticsearch:7.9.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200